# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('pelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamanio', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='fotos/mascotas/')),
            ],
        ),
    ]
